# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins:
  - bourbon
  - neat

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

include:
  - _pages
  - _redirects

# Site settings
title: Matt Grey
email: mattgreydesign@gmail.com
description: "Portfolio of UX, font and graphic designer Matt Grey"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://himatt.com" # the base hostname & protocol for your site
timezone: Europe/London
year: 2018
sitemap: true

# Social networks
social-username:
  twitter: "@mattgreydesign"
  linkedin: "himatt"
  github: "mattgreydesign"
  medium: "@mattgreydesign"
  pinterest: "mattgreydesign"
  instagram: "mattgreydesign"
  flickr: "mattgreydesign"
  spotify: "mattgreydesign"
  lastfm: "mattdabest"

# Content
image_serve_path: "/images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  blanklines: false # boolean - strip blank lines and breaks
  #profile: true # boolean - print table of data saved
  #ignore:
  #envs: [local]

# Structure
navigation:
  - title: Projects
    url: /
  - title: Fonts
    url: /fonts
  - title: About
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  fonts:
    output: false
    permalink: /fonts/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  # - scope:
  #     path: ""
  #     type: "fonts"
  #   values:
  #     layout: "font"
